//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatingParameters_Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperatingParameters_Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL PROCESSING ERROR 002: A parameter type information element format is incorrect; the field count differs from the expected field count.{3}    Expected field count = {0}{3}    Actual field count   = {1}{3}    Actual detail record = {2}{3}.
        /// </summary>
        public static string ERRMSG_INTERNAL_PROCESSING_ERROR_002 {
            get {
                return ResourceManager.GetString("ERRMSG_INTERNAL_PROCESSING_ERROR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL PROCESSING ERROR 004: A parameter type information element name is incorrect; the {0} value is undefined and unsupported.{1}.
        /// </summary>
        public static string ERRMSG_INTERNAL_PROCESSING_ERROR_004 {
            get {
                return ResourceManager.GetString("ERRMSG_INTERNAL_PROCESSING_ERROR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL PROCESSING ERROR 005: Type information for the {0} parameter cannot be found in the embedded {1} resource.{2}.
        /// </summary>
        public static string ERRMSG_INTERNAL_PROCESSING_ERROR_005 {
            get {
                return ResourceManager.GetString("ERRMSG_INTERNAL_PROCESSING_ERROR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration {0} value of {1} is invalid..
        /// </summary>
        public static string ERRMSG_INVALID_PARAMETER_TYPE {
            get {
                return ResourceManager.GetString("ERRMSG_INVALID_PARAMETER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument name &apos;{0}&apos; is undefined..
        /// </summary>
        public static string ERRMSG_UNDEFINED_ARGNAME {
            get {
                return ResourceManager.GetString("ERRMSG_UNDEFINED_ARGNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSetting # {0,2}: Name         = {1}{4}                 PropertyType = {2}{4}                 DefaultValue = {3}{4}.
        /// </summary>
        public static string MESSAGE_APPSETTING_VALUE {
            get {
                return ResourceManager.GetString("MESSAGE_APPSETTING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seetings count = {0}:{1}.
        /// </summary>
        public static string MESSAGE_APPSETTINGS_FOOTER {
            get {
                return ResourceManager.GetString("MESSAGE_APPSETTINGS_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Application Setting Defaults for {0}:{1}.
        /// </summary>
        public static string MESSAGE_APPSETTINGS_HEADER {
            get {
                return ResourceManager.GetString("MESSAGE_APPSETTINGS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}Application Settings Value for Parameter {0} = {1}{2}.
        /// </summary>
        public static string MESSAGE_DEFALUT_PER_APP_SETTINGS {
            get {
                return ResourceManager.GetString("MESSAGE_DEFALUT_PER_APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSetting # {0,2}: Name         = {1}{4}                   PropertyType = {2}{4}                   DefaultValue = {3}{4}.
        /// </summary>
        public static string MESSAGE_DEFINED_APPSETTINGS {
            get {
                return ResourceManager.GetString("MESSAGE_DEFINED_APPSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{4}    Column Name  = {1}{4}    Column Index = {2}{4}    Whole Record = {3}{4}.
        /// </summary>
        public static string MESSAGE_INVALID_PARAMETER_TYPE_VALUE {
            get {
                return ResourceManager.GetString("MESSAGE_INVALID_PARAMETER_TYPE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings property &apos;{0}&apos; was not found..
        /// </summary>
        public static string MESSAGE_NO_DEFAULT_IN_APP_SETTINGS {
            get {
                return ResourceManager.GetString("MESSAGE_NO_DEFAULT_IN_APP_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}There is no default value in the application settings for the &apos;{0}&apos; parameter.{1}.
        /// </summary>
        public static string MESSAGE_NO_DEFAULT_VALUE {
            get {
                return ResourceManager.GetString("MESSAGE_NO_DEFAULT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Parameter # {0}: {1}.
        /// </summary>
        public static string MESSAGE_PARAMETER_NAME {
            get {
                return ResourceManager.GetString("MESSAGE_PARAMETER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Resource # {0}: {1}.
        /// </summary>
        public static string MESSAGE_RESOURCE_NAMES_DETAIL {
            get {
                return ResourceManager.GetString("MESSAGE_RESOURCE_NAMES_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Count of resources stored in assembly = {0}{1}.
        /// </summary>
        public static string MESSAGE_RESOURCE_NAMES_FOOTER {
            get {
                return ResourceManager.GetString("MESSAGE_RESOURCE_NAMES_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Resources Stored in Assembly {0}:{1}.
        /// </summary>
        public static string MESSAGE_RESOURCE_NAMES_HEADER {
            get {
                return ResourceManager.GetString("MESSAGE_RESOURCE_NAMES_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of Application Settings property type mismatch:{4}    Settings property name  = {0}{4}    Settings property type  = {1}{4}    Expected settings type  = {2}{4}    Settings property value = {3}{4}.
        /// </summary>
        public static string MESSAGE_UNEXPECTED_SETTINGS_TYPE {
            get {
                return ResourceManager.GetString("MESSAGE_UNEXPECTED_SETTINGS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of {0} parameter list.{1}.
        /// </summary>
        public static string MSG_PARAMETER_LIST_FOOTER {
            get {
                return ResourceManager.GetString("MSG_PARAMETER_LIST_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} application has {1} parameters.{2}.
        /// </summary>
        public static string MSG_PARAMETER_LIST_HEADER {
            get {
                return ResourceManager.GetString("MSG_PARAMETER_LIST_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Operating Parameters:{0}.
        /// </summary>
        public static string MSG_VALIDATION_BEGIN {
            get {
                return ResourceManager.GetString("MSG_VALIDATION_BEGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} value of {1} is {2}..
        /// </summary>
        public static string MSG_VALIDATION_DETAIL {
            get {
                return ResourceManager.GetString("MSG_VALIDATION_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}End of Paramater Validation Report{0}.
        /// </summary>
        public static string MSG_VALIDATION_END {
            get {
                return ResourceManager.GetString("MSG_VALIDATION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: InternalName = {1}{9}DisplayName = {2}{9}ParamValue = {3}{9}ParamType = {4}{9}HasDefaultValueInAppSettings = {5}{9}ParamState = {6}{9}ParamSource = {7}{9}SavedDefaultValue = {8}.
        /// </summary>
        public static string OPERATING_PARAMETER_TOSTRING {
            get {
                return ResourceManager.GetString("OPERATING_PARAMETER_TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Parameter # 1 of 3.
        /// </summary>
        public static string PARAM_DISPLAY_NAME_OperatingParameter1 {
            get {
                return ResourceManager.GetString("PARAM_DISPLAY_NAME_OperatingParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter # 3 of 3.
        /// </summary>
        public static string PARAM_DISPLAY_NAME_OperatingParameter3 {
            get {
                return ResourceManager.GetString("PARAM_DISPLAY_NAME_OperatingParameter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAM_DISPLAY_NAME_{0}.
        /// </summary>
        public static string PARAMETER_DISPLAY_NAME_TEMPLATE {
            get {
                return ResourceManager.GetString("PARAMETER_DISPLAY_NAME_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Empty].
        /// </summary>
        public static string RENDERED_STRING_IS_EMPTY {
            get {
                return ResourceManager.GetString("RENDERED_STRING_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Null].
        /// </summary>
        public static string RENDERED_STRING_IS_NULL {
            get {
                return ResourceManager.GetString("RENDERED_STRING_IS_NULL", resourceCulture);
            }
        }
    }
}
